Metrics

diff --git a/.github/workflows/PracticaGitHubActions.yml b/.github/workflows/PracticaGitHubActions.yml
--- a/.github/workflows/PracticaGitHubActions.yml
+++ b/.github/workflows/PracticaGitHubActions.yml
@@ -107,3 +107,35 @@ jobs:
           git rebase origin/main || (git rebase --abort && echo "Rebase failed; skipping rebase")
           git push origin main || echo "Push failed; skipping push"
         
+          
+          
+  metrics_job:
+    needs: cypress_job
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Generate GitHub metrics
+        uses: lowlighter/metrics@latest
+        with:
+          filename: github-metrics.svg
+          token: ${{ secrets.TOKENGITHUB }}
+          base: ""
+          plugin_languages: yes
+          plugin_languages_ignored: >-
+            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
+            gnuplot
+          plugin_languages_limit: 4
+
+      - name: Update README with metrics
+        run: |
+          echo "Updating README.md with metrics..."
+          awk '/## Resultados de Métricas/ {print; print "![Metrics](github-metrics.svg)"; next} 1' README.md > temp.md && mv temp.md README.md
+          git config --global user.email "alvgarcam@alu.edu.gva.es"
+          git config --global user.name "AlvaroGarCam"
+          git add README.md
+          git commit -m "Update README.md with static GitHub metrics" || echo "No changes to commit"
+          git fetch origin main
+          git rebase origin/main || (git rebase --abort && echo "Rebase failed; skipping pull step")
+          git push origin main || echo "Push failed; skipping push"
